language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
before_install:
  - composer self-update
install:
  - composer install --no-interaction --prefer-source
  - ./scripts/fixtures.sh
script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpunit
