language: php
php:
  - "5.5"
  - "5.4"
before_install:
  - composer self-update
install:
  - composer install --no-interaction --prefer-source
  - ./scripts/fixtures.sh
script:
  - ./vendor/bin/phpspec
  - ./vendor/bin/phpunit
